const { Album } = require('../models');

const albumData = [

  //ROCK AND ROLL BABYYYY
  {
    album_name: 'Dark Side of the Moon',
    artist_name: 'Pink Floyd',
    released: '01/03/1973',
    label: 'Harvest',
    length: '43:09',
    cover: 'Dark_Side_of_the_Moon.png',
    amazon_image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01LTHN0DG/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01LTHN0DG&linkCode=as2&tag=tunescope-20&linkId=971a569f0c40d880c4bacaaac0d7552b"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01LTHN0DG&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=tunescope-20" ></a>',
    amazon_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=tunescope-20&marketplace=amazon&amp;region=US&placement=B01LTHN0DG&asins=B01LTHN0DG&linkId=9e8ddce52707ca4e5173b77e138e31e1&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=a7a7f0&bg_color=ffffff"></iframe>',
    spotify_embed: '<iframe src="https://open.spotify.com/embed/album/4LH4d3cOWNNsVw41Gqt2kv?theme=0" width="100%" height="380" frameBorder="0" allowtransparency="true" allow="encrypted-media"></iframe>',
    genre_id: 1,
  },
  {
    album_name: 'Wish You Were Here',
    artist_name: 'Pink Floyd',
    released: '12/09/1975',
    label: 'Harvest',
    length: '44:11',
    cover: 'Pink_Floyd,_Wish_You_Were_Here_(1975).png',
    amazon_image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B019HKJW4S/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B019HKJW4S&linkCode=as2&tag=tunescope-20&linkId=8e3d875d10506b03a9155f8a93b68adb"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B019HKJW4S&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=tunescope-20" ></a>',
    amazon_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=tunescope-20&marketplace=amazon&amp;region=US&placement=B00536OCZK&asins=B00536OCZK&linkId=9bac490cc9e011a8ad999ba582ca2e6e&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=000000&bg_color=ffffff"></iframe>',
    spotify_embed: '<iframe src="https://open.spotify.com/embed/album/0bCAjiUamIFqKJsekOYuRw?theme=0" width="100%" height="380" frameBorder="0" allowtransparency="true" allow="encrypted-media"></iframe>',
    genre_id: 1,
  },
  {
    album_name: 'The Wall',
    artist_name: 'Pink Floyd',
    released: '30/11/1979',
    label: 'Harvest/Columbia',
    length: '81:08',
    cover: 'PinkFloydWallCoverOriginalNoText-2.jpg',
    amazon_image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B019HKKVDE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B019HKKVDE&linkCode=as2&tag=tunescope-20&linkId=d7ca28e011827a02ea779e540ad8be73"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B019HKKVDE&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=tunescope-20" ></a>',
    amazon_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=tunescope-20&marketplace=amazon&amp;region=US&placement=B00536OCYG&asins=B00536OCYG&linkId=2e54548ac0f121b397f8a92c06725191&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=000000&bg_color=ffffff"></iframe>',
    spotify_embed: '<iframe src="https://open.spotify.com/embed/album/5Dbax7G8SWrP9xyzkOvy2F?theme=0" width="100%" height="380" frameBorder="0" allowtransparency="true" allow="encrypted-media"></iframe>',
    genre_id: 1,
  },
  {
    album_name: 'Led Zeppelin',
    artist_name: 'Led Zeppelin',
    released: '12/01/1969',
    label: 'Atlantic',
    length: '44:56',
    cover: 'Led_Zeppelin_-_Led_Zeppelin_(1969)_front_cover.png',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '<iframe src="https://open.spotify.com/embed/album/5Dbax7G8SWrP9xyzkOvy2F?theme=0" width="100%" height="380" frameBorder="0" allowtransparency="true" allow="encrypted-media"></iframe>',
    genre_id: 1,
  },
  {
    album_name: 'Led Zeppelin II',
    artist_name: 'Led Zeppelin',
    released: '22/10/1969',
    label: 'Atlantic',
    length: '41:38',
    cover: 'Led_Zeppelin_-_Led_Zeppelin_II.jpg',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },
  {
    album_name: 'Led Zeppelin III',
    artist_name: 'Led Zeppelin',
    released: '05/10/1970',
    label: 'Atlantic',
    length: '43:04',
    cover: 'Led_Zeppelin_-_Led_Zeppelin_III.png',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },
  {
    album_name: 'Led Zeppelin IV',
    artist_name: 'Led Zeppelin',
    released: '08/11/1971',
    label: 'Atlantic',
    length: '42:34',
    cover: 'Led_Zeppelin_-_Led_Zeppelin_IV',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },
  {
    album_name: 'Houses of the Holy',
    artist_name: 'Led Zeppelin',
    released: '28/03/1973',
    label: 'Atlantic',
    length: '42:34',
    cover: 'Led_Zeppelin_-_Houses_of_the_Holy.jpg',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },
  {
    album_name: 'Physical Graffiti',
    artist_name: 'Led Zeppelin',
    released: '24/02/1975',
    label: 'Atlantic',
    length: '82:59',
    cover: 'Led_Zeppelin_-_Physical_Graffiti',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },
  {
    album_name: 'Appetite for Destruction',
    artist_name: 'Guns N\' Roses',
    released: '21/07/1987',
    label: 'Geffen',
    length: '53:52',
    cover: 'GunsnRosesAppetiteforDestructionalbumcover.jpg',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },
  {
    album_name: 'Audioslave',
    artist_name: 'Audioslave',
    released: '18/11/2002',
    label: 'Epic/Interscope',
    length: '65:26',
    cover: 'Audioslave_-_Audioslave.jpg',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },
  {
    album_name: 'New Levels New Devils',
    artist_name: 'Polyphia',
    released: '12/10/2018',
    label: 'Equal Vision',
    length: '36:54',
    cover: 'New-Levels-Polyphia.png',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },
  {
    album_name: 'Back in Black',
    artist_name: 'AC/DC',
    released: '25/07/1980',
    label: 'Albert/Atlantic',
    length: '42:11',
    cover: '440px-ACDC_Back_in_Black.png',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },
  {
    album_name: 'The Battle at Garden\'s Gate',
    artist_name: 'Greta Van Fleet',
    released: '16/04/2021',
    label: 'Lava/Republic',
    length: '63:32',
    cover: 'Greta_Van_Fleet_-_The_Battle_at_Garden\'s_Gate.png',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },
  {
    album_name: 'Revolver',
    artist_name: 'The Beatles',
    released: '05/08/1966',
    label: 'Parlaphone',
    length: '35:01',
    cover: 'Revolver_(album_cover).jpg',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },
  {
    album_name: 'Let It Be',
    artist_name: 'The Beatles',
    released: '08/05/1970',
    label: 'Apple',
    length: '35:10',
    cover: 'LetItBe.jpg',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },
  {
    album_name: 'Sgt. Pepper\'s Lonely Hearts Club Band',
    artist_name: 'The Beatles',
    released: '26/05/1967',
    label: 'Parlaphone',
    length: '39:36',
    cover: 'Sgt._Pepper\'s_Lonely_Hearts_Club_Band.jpg',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },
  {
    album_name: 'Abbey Road',
    artist_name: 'The Beatles',
    released: '26/09/1969',
    label: 'Apple',
    length: '47:03',
    cover: 'Beatles_-_Abbey_Road.jpg',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },
  {
    album_name: 'Daddy\'s Home',
    artist_name: 'St. Vincent',
    released: '14/05/2021',
    label: 'Loma Vista',
    length: '43:09',
    cover: 'St._Vincent_-_Daddy\'s_Home.png',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },
  {
    album_name: 'Tubular Bells',
    artist_name: 'Mike Oldfield',
    released: '25/05/1973',
    label: 'Virgin',
    length: '49:16',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },
  {
    album_name: '',
    artist_name: '',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 1,
  },

//METALLLLL
  {
    album_name: 'Infest the Rat\'s Nest',
    artist_name: 'King Gizzard & the Lizard Wizard',
    released: '16/08/2019',
    label: 'Flightless/ATO',
    length: '34:50',
    cover: 'King_Gizzard_&_the_Lizard_Wizard_-_Infest_the_Rats\'_Nest.png',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 2,
  },
  {
    album_name: 'Master of Puppets',
    artist_name: 'Metallica',
    released: '03/03/1986',
    label: 'Elekra',
    length: '54:47',
    cover: 'Metallica_-_Master_of_Puppets_cover.jpg',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 2,
  },
  {
    album_name: 'Kill Em All',
    artist_name: 'Metallica',
    released: '25/07/1983',
    label: 'Megaforce',
    length: '51:20',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 2,
  },
  {
    album_name: 'Ride The Lightning',
    artist_name: 'Metallica',
    released: '27/07/1984',
    label: 'Megaforce',
    length: '47:25',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 2,
  },
  {
    album_name: 'Peace Sells...but Who\'s Buying?',
    artist_name: 'Megadeth',
    released: '19/09/1986',
    label: 'Capitol',
    length: '36:12',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 2,
  },
  {
    album_name: 'Reign in Blood',
    artist_name: 'Slayer',
    released: '07/10/1986',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 2,
  },
  {
    album_name: 'The Number of the Beast',
    artist_name: 'Iron Maiden',
    released: '22/03/1982',
    label: 'EMI',
    length: '39:11',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 2,
  },
  {
    album_name: 'Paranoid',
    artist_name: 'Black Sabbath',
    released: '18/09/1970',
    label: 'Vertigo/Warner Bros.',
    length: '41:51',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 2,
  },
  {
    album_name: 'Black Sabbath',
    artist_name: 'Black Sabbath',
    released: '13/02/1970',
    label: 'Vertigo',
    length: '38:08',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 2,
  },
  {
    album_name: 'British Steel',
    artist_name: 'Judas Priest',
    released: '14/04/1980',
    label: 'Columbia',
    length: '36:10',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 2,
  },

//POPPPPPP
  {
    album_name: 'Future Nostalgia',
    artist_name: 'Dua Lipa',
    released: '27/03/2020',
    label: 'Warner',
    length: '37:17',
    cover: 'Dua_Lipa_-_Future_Nostalgia_(Official_Album_Cover)',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 3,
  },
  {
    album_name: 'Plastic Hearts',
    artist_name: 'Miley Cyrus',
    released: '27/11/2020',
    label: 'RCA',
    length: '38:15',
    cover: 'Miley_Cyrus_-_Plastic_Hearts.png',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 3,
  },
  {
    album_name: 'Sour',
    artist_name: 'Olivia Rodrigo',
    released: '21/05/2021',
    label: 'Geffen',
    length: '34:41',
    cover: 'Olivia_Rodrigo_-_SOUR.png',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 3,
  },
  {
    album_name: 'When We All Fall Asleep, Where Do We Go?',
    artist_name: 'Billie Eilish',
    released: '29/03/2019',
    label: 'Darkroom/Interscope',
    length: '42:56',
    cover: 'When_We_All_Fall_Asleep,_Where_Do_We_Go?.png',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 3,
  },
  {
    album_name: '21',
    artist_name: 'Adele',
    released: '24/01/2011',
    label: 'XL/Columbia',
    length: '48:01',
    cover: 'Adele_-_21.png',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 3,
  },
  {
    album_name: 'WILLOW',
    artist_name: 'Willow',
    released: '19/07/2019',
    label: 'MSFTS/Roc Nation',
    length: '47:03',
    cover: 'WillowSelfTitled.jpg',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 3,
  },
  {
    album_name: 'The Slow Rush',
    artist_name: 'Tame Impala',
    released: '14/02/2020',
    label: 'Modular/Island Australia/Interscope',
    length: '57:16',
    cover: 'Tame_Impala_-_The_Slow_Rush-2.png',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 3,
  },
  {
    album_name: 'Curents',
    artist_name: 'Tame Impala',
    released: '17/07/2015',
    label: 'Modular/Interscope',
    length: '51:12',
    cover: 'Tame_Impala_-_Currents.png',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 3,
  },
  {
    album_name: 'Pretty. Odd.',
    artist_name: 'Panic! At The Disco',
    released: '21/03/2008',
    label: 'Decaydance/Fueled by Ramen',
    length: '48:46',
    cover: 'PatD_-_Pretty._Odd..jpg',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 3,
  },
  {
    album_name: 'Trench',
    artist_name: 'Twenty One Pilots',
    released: '05/10/2018',
    label: 'Fueled by Ramen/Elekra',
    length: '56:04',
    cover: 'Trench_Twenty_One_Pilots.png',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 3,
  },

  //ELECTRONIC
  {
    album_name: 'Neon Future III',
    artist_name: 'Steve Aoki',
    released: '09/09/2018',
    label: 'Ultra/Dim Mak',
    length: '57:05',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 4,
  },
  {
    album_name: 'Nurture',
    artist_name: 'Porter Robinson',
    released: '23/04/2021',
    label: 'Mom + Pop',
    length: '59:01',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 4,
  },
  {
    album_name: '4x4=12',
    artist_name: 'deadmau5',
    released: '06/12/2010',
    label: 'Virgin/Ultra/Mau5trap',
    length: '69:54',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 4,
  },
  {
    album_name: 'Bangarang',
    artist_name: 'Skrillex',
    released: '23/12/2011',
    label: 'Atlantic/Big Beat/Owsla',
    length: '30:08',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 4,
  },
  {
    album_name: 'Daft Punk',
    artist_name: 'Homework',
    released: '20/01/1997',
    label: 'Virgin/Soma',
    length: '73:53',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 4,
  },
  {
    album_name: 'Dig Your Own Hole',
    artist_name: 'The Chemical Brothers',
    released: '07/04/1997',
    label: 'Virgin',
    length: '63:27',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 4,
  },
  {
    album_name: 'Play',
    artist_name: 'Moby',
    released: '17/05/1999',
    label: 'Mute/V2',
    length: '62:37',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 4,
  },
  {
    album_name: 'Computerwelt',
    artist_name: 'Kraftwerk',
    released: '10/05/1981',
    label: 'Warner Bros./Kling Klang',
    length: '34:21',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 4,
  },
  {
    album_name: 'Blue Lines',
    artist_name: 'Massive Attack',
    released: '08/04/1991',
    label: 'Virgin/Trip Hop',
    length: '45:04',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 4,
  },
  {
    album_name: 'Volume Alpha',
    artist_name: 'Minecraft',
    released: '04/03/2011',
    label: 'N/A',
    length: '58:59',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 4,
  },

  //R&B/BLUES/SOUL
  {
    album_name: 'Back to Black',
    artist_name: 'Amy Winehouse',
    released: '27/10/2006',
    label: 'Island',
    length: '34:56',
    cover: 'Amy_Winehouse_-_Back_to_Black_(album).png',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 5,
  },
  {
    album_name: 'Tattoo',
    artist_name: 'Rory Gallagher',
    released: '11/11/1973',
    label: 'Polydor',
    length: '58:52',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 5,
  },
  {
    album_name: 'What\'s Going On',
    artist_name: 'Marvin Gaye',
    released: '21/05/1971',
    label: 'Tamla',
    length: '35:38',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 5,
  },
  {
    album_name: 'Songs in the Key of Life',
    artist_name: 'Stevie Wonder',
    released: '28/09/1976',
    label: 'Tamla',
    length: '104:29',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 5,
  },
  {
    album_name: 'One Dozen Berrys',
    artist_name: 'Chuck Berry',
    released: '00/03/1958',
    label: 'Chess',
    length: '34:24',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 5,
  },
  {
    album_name: 'Completely Well',
    artist_name: 'B.B. King',
    released: '05/12/1969',
    label: 'BluesWay',
    length: '49:57',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 5,
  },
  {
    album_name: 'Texas Flood',
    artist_name: 'Stevie Ray Vaughn',
    released: '13/06/1983',
    label: 'Epic',
    length: '38:48',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 5,
  },
  {
    album_name: 'Born Under a Bad Sign',
    artist_name: 'Albert King',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 5,
  },
  {
    album_name: 'King of the Delta Blues Singers',
    artist_name: 'Robert Johnson',
    released: '00/00/1961',
    label: 'Columbia',
    length: '43:08',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 5,
  },
  {
    album_name: 'Night Beat',
    artist_name: 'Sam Cooke',
    released: '00/08/1963',
    label: 'RCA Victor',
    length: '37:51',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 5,
  },

  //JAZZ?
  {
    album_name: 'Kind of Blue',
    artist_name: 'Miles Davis',
    released: '17/08/1959',
    label: 'Columbia',
    length: '45:44',
    cover: 'MilesDavisKindofBlue.jpg',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 6,
  },
  {
    album_name: 'A Love Supreme',
    artist_name: 'John Coltrane',
    released: '00/01/1965',
    label: 'Impulse!',
    length: '33:02',
    cover: 'John_Coltrane_-_A_Love_Supreme.jpg',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 6,
  },
  {
    album_name: 'Jaco Pastorius',
    artist_name: 'Jaco Pastorius',
    released: '00/08/1976',
    label: 'Epic/Legacy',
    length: '42:09',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 6,
  },
  {
    album_name: 'Mingus Ah Um',
    artist_name: 'Charles Mingus',
    released: '00/10/1959',
    label: 'Columbia',
    length: '50:53',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 6,
  },
  {
    album_name: 'Like Minds',
    artist_name: 'Corea, Metheny, Haynes, Holland',
    released: '00/00/1998',
    label: 'Concord',
    length: '68:25',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 6,
  },
  {
    album_name: 'Head Hunters',
    artist_name: 'Herbie Hancock',
    released: '26/10/1973',
    label: 'Columbia',
    length: '41:52',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 6,
  },
  {
    album_name: 'Th Shape of Jazz to Come',
    artist_name: 'Ornette Coleman',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 6,
  },
  {
    album_name: 'Saxophone Colossus',
    artist_name: 'Sonny Rollins',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 6,
  },
  {
    album_name: 'Lady in Satin',
    artist_name: 'Billie Holiday',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 6,
  },
  {
    album_name: 'Bitches Brew',
    artist_name: 'Miles Davis',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 6,
  },

//CLASSICAL FANCY FANCY
  {
    album_name: 'The Planets',
    artist_name: 'Gustav Holst',
    released: '29/09/1918',
    label: 'N/A',
    length: '52:02',
    cover: 'theplanets.jpg',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 7,
  },
  {
    album_name: 'Rite of Spring',
    artist_name: 'Stravinsky',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 7,
  },
  {
    album_name: 'Rhapsody in Blue',
    artist_name: 'Gershwin',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 7,
  },
  {
    album_name: 'Piano Protagonists',
    artist_name: 'The Orchestra Now',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 7,
  },
  {
    album_name: 'Star Wars: Episode IV: A New Hope',
    artist_name: 'John Williams',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 7,
  },
  {
    album_name: 'Symphonies Nos 5 & 7',
    artist_name: 'Beethoven',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 7,
  },
  {
    album_name: 'War Requiem',
    artist_name: 'Benjamin Britten',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 7,
  },
  {
    album_name: 'Goldberg Variations',
    artist_name: 'JS Bach',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 7,
  },
  {
    album_name: 'Symphonies Nos 4 & 6',
    artist_name: 'Tchaikovsky',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 7,
  },
  {
    album_name: 'The Yellow Shark',
    artist_name: 'Frank Zappa',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 7,
  },

// country
  {
    album_name: 'At Folsom Prison',
    artist_name: 'Johnny Cash',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 8,
  },
  {
    album_name: 'Modern Sounds in Country and Western Music',
    artist_name: 'Ray Charles',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 8,
  },
  {
    album_name: 'Red Headed Stranger',
    artist_name: 'Willie Nelson',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 8,
  },
  {
    album_name: 'Dolly Parton',
    artist_name: 'Coat of Many Colors',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 8,
  },
  {
    album_name: 'I\'m a Lonesome Fugitive',
    artist_name: 'Merle Haggard',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 8,
  },
  {
    album_name: 'Van Lear Rose',
    artist_name: 'Loretta Lynn',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 8,
  },
  {
    album_name: 'Ropin\' the Wind',
    artist_name: 'Garth Brooks',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 8,
  },
  {
    album_name: 'Kristofferson',
    artist_name: 'Kris Kristofferson',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 8,
  },
  {
    album_name: 'The Gambler',
    artist_name: 'Kenny Rogers',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 8,
  },
  {
    album_name: 'Man In Black',
    artist_name: 'Johnny Cash',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 8,
  },

//RAP
  {
    album_name: 'Kanye West',
    artist_name: 'My Beautiful Dark Twisted Fantasy',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 9,
  },
  {
    album_name: 'Kendrick Lamar',
    artist_name: 'To Pimp a Butterfly',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 9,
  },
  {
    album_name: 'The Beastie Boys',
    artist_name: 'License to Ill',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 9,
  },
  {
    album_name: 'Straight Outta Compton',
    artist_name: 'N.W.A.',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 9,
  },
  {
    album_name: 'It Takes A Nation Of Millions To Hold Us Back',
    artist_name: 'Public Enemy',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 9,
  },
  {
    album_name: 'The Low End Theory',
    artist_name: 'A Tribe Called Quest',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 9,
  },
  {
    album_name: 'The Marshall Mathers LP',
    artist_name: 'Eminem',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 9,
  },
  {
    album_name: 'The Chronic',
    artist_name: 'Dr. Dre',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 9,
  },
  {
    album_name: 'Enter The Wu-Tang(36 Chambers)',
    artist_name: 'Wu-Tang Clan',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 9,
  },
  {
    album_name: 'Ready To Die',
    artist_name: 'The Notorious BIG',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 9,
  },
  {
    album_name: 'All Eyez On Me',
    artist_name: '2Pac',
    released: '//',
    label: '',
    length: ':',
    cover: '',
    amazon_image_link: '',
    amazon_link: '',
    spotify_embed: '',
    genre_id: 9,
  },
];

const seedProducts = () => Album.bulkCreate(albumData);

module.exports = seedProducts;
